config/routes.rb
Rails.application.routes.draw do
  resources :boards
  root 'boards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all.order(created_at: 'desc')
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3>スレッド名</h3>
    <%= form.text_field :title, class: 'thread_title' %>
  </div>

  <div class="actions">
    <%#= form.submit %>
    <button type='submit' value='更新'>更新</button>
    <button onclick='history.back()'>戻る</button>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1><%= @board.title %></h1>

<%= render 'form', board: @board %>

<%#= link_to '終了', @board %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>掲示板</h1>
<p><%= link_to '新しいスレッドを作る', new_board_path, class: 'menu' %></p>
<br/><br/>

<table>
  <thead>
    <tr>
      <th></th>
      <th><h3>スレッド名</h3></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to '[x️]', board_path(board.id), method: :delete, data: { confirm: "スレッド名: #{board.title}を削除しますか?" }, class: 'delete_button' %></td>
        <td class="thread_title"><%= board.title %></td>
<!--        <td class="thread_content"><%#= board.body %></td>-->
        <td><%= link_to '詳細', board_path(board.id) %></td>
<!--        <td><%#= link_to '編集', edit_board_path(board.id) %></td>-->
        <!--削除するときにスレッド名を表示する-->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h1>新しい掲示板</h1>

<%= render 'form', board: @board %>

<%= link_to 'キャンセル', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<h3>スレッド名: <%= @board.title %></h3>

<%= link_to '編集', edit_board_path(@board) %> |
<%= link_to '戻る', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreadBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>